// Auto-generated from the three survey exports (English, French, Arabic).
// Only anonymous, categorical responses and curated excerpts are included.
// No names, usernames, or contact information exist in this file.
window.SURVEY = {
 "meta": {
  "n_total": 162,
  "n_by_lang": {
   "English": 118,
   "French": 32,
   "Arabic": 12
  },
  "equality_mean": 4.6,
  "equality_median": 4.0,
  "open_ended_substantive": 65,
  "voices_total": 71
 },
 "records": [
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Prefer not to say",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "International school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "University student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 6,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "Before 6 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Prefer not to say",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Prefer not to say",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Prefer not to say",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Prefer not to say",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Other",
   "age": "18-20",
   "region": "Tanger-Tétouan-Al Hoceïma",
   "location": "Big city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 7,
   "beauty_pressure": "None",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "University student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "6-7 PM",
   "equality": 6,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 6,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Marrakech-Safi",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "None",
   "body_judged": "Prefer not to say",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Prefer not to say",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Marrakech-Safi",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Guelmim-Oued Noun",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 8,
   "beauty_pressure": "A lot",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 8,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Marrakech-Safi",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Prefer not to say",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Rural area",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Prefer not to say",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Prefer not to say",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "20-25",
   "region": "Marrakech-Safi",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 10,
   "beauty_pressure": "None",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "20-25",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "None",
   "body_judged": "Prefer not to say",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Prefer not to say",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 6,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "After 12 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Tanger-Tétouan-Al Hoceïma",
   "location": "Big city",
   "education": "University student",
   "harassment": "Prefer not to say",
   "curfew": "10-12 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 5,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Prefer not to say",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "10-12 PM",
   "equality": 2,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Souss-Massa",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "English",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "20-25",
   "region": "Oriental",
   "location": "Rural area",
   "education": "University student",
   "harassment": "No",
   "curfew": "6-7 PM",
   "equality": 6,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "18-20",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "International school student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 5,
   "beauty_pressure": "None",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "Other",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Working / employed",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "Other",
   "region": "Fès-Meknès",
   "location": "Town / Small city",
   "education": "Working / employed",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "No",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "French",
   "gender": "Prefer not to say",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "Before 6 PM",
   "equality": 10,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "International school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 2,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Casablanca-Settat",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "Other",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Working / employed",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 8,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "Before 6 PM",
   "equality": 4,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Never"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Prefer not to say",
   "curfew": "Before 6 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "Before 6 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "Before 6 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 8,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 5,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "20-25",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "20-25",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 8,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "20-25",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "No",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 6,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "6-7 PM",
   "equality": 7,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "20-25",
   "region": "Casablanca-Settat",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Never"
  },
  {
   "lang": "French",
   "gender": "Female",
   "age": "18-20",
   "region": "Fès-Meknès",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 3,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "French",
   "gender": "Male",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "10-12 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "Arabic",
   "gender": "Male",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 2,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "Arabic",
   "gender": "Male",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 3,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "Barely",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "Arabic",
   "gender": "Male",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "No",
   "curfew": "8-9 PM",
   "equality": 8,
   "beauty_pressure": "None",
   "body_judged": "Prefer not to say",
   "family_diff": "No",
   "consent_edu": "Yes",
   "know_victim": "No",
   "walking_alone": "Always"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Marrakech-Safi",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 7,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "20-25",
   "region": "Drâa-Tafilalet",
   "location": "Town / Small city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 8,
   "beauty_pressure": "None",
   "body_judged": "Yes",
   "family_diff": "No",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Marrakech-Safi",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "6-7 PM",
   "equality": 4,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "No",
   "know_victim": "No",
   "walking_alone": "Rarely"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "18-20",
   "region": "Rabat-Salé-Kénitra",
   "location": "Big city",
   "education": "University student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Barely",
   "know_victim": "Yes",
   "walking_alone": "Most of the time"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Fès-Meknès",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "No",
   "curfew": "After 12 PM",
   "equality": 8,
   "beauty_pressure": "Not that much",
   "body_judged": "Prefer not to say",
   "family_diff": "No",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Always"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Béni Mellal-Khénifra",
   "location": "Town / Small city",
   "education": "Public school student",
   "harassment": "No",
   "curfew": "Before 6 PM",
   "equality": 1,
   "beauty_pressure": "A lot",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Prefer not to say",
   "walking_alone": "Never"
  },
  {
   "lang": "Arabic",
   "gender": "Female",
   "age": "14-17",
   "region": "Rabat-Salé-Kénitra",
   "location": "Town / Small city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "8-9 PM",
   "equality": 5,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Not applicable",
   "consent_edu": "No",
   "know_victim": "Yes",
   "walking_alone": "Rarely"
  },
  {
   "lang": "Arabic",
   "gender": "Male",
   "age": "14-17",
   "region": "Souss-Massa",
   "location": "Big city",
   "education": "Private school student",
   "harassment": "Yes",
   "curfew": "After 12 PM",
   "equality": 6,
   "beauty_pressure": "Not that much",
   "body_judged": "Yes",
   "family_diff": "Yes",
   "consent_edu": "Yes",
   "know_victim": "Yes",
   "walking_alone": "Always"
  }
 ],
 "voices": [
  {
   "theme": "School & classroom",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "In school, during group projects, some teachers usually picked the boys as the “leaders”, while girls were often just asked to organize or write. Even when we had good ideas, they were sometimes ignored."
  },
  {
   "theme": "School & classroom",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "We had to debate about gender equality and the teacher only let boys speak, even though girls wanted to debate too."
  },
  {
   "theme": "School & classroom",
   "lang": "English",
   "who": "Male, 14–17",
   "text": "Honestly it goes the other way in my school — teachers tend to be gentler with the girls."
  },
  {
   "theme": "Sports & PE",
   "lang": "English",
   "who": "Female, 18–20",
   "text": "During sports I was treated like a weak person, generally put aside from the guys and told to just play with the other girls."
  },
  {
   "theme": "Sports & PE",
   "lang": "French",
   "who": "Female, 14–17",
   "text": "À chaque contrôle d’éducation physique, les filles ne font qu’un tour de terrain alors que les garçons en font trois. Le prof m’a répondu que c’est parce que les filles n’ont pas assez de force.",
   "translation": "At every PE test, girls only run one lap of the field while boys run three. When I asked why, the teacher said it’s because girls aren’t strong enough."
  },
  {
   "theme": "Mobility & going out",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "During hangouts I have to update my parents every 10 minutes about where I am. When I ask about small jobs after 6pm they say ‘no, you’re a girl’."
  },
  {
   "theme": "Mobility & going out",
   "lang": "English",
   "who": "Female, 18–20",
   "text": "It feels very awkward and scary for me as a girl to go out alone at night."
  },
  {
   "theme": "Mobility & going out",
   "lang": "French",
   "who": "Female, 14–17",
   "text": "Quand il s’agit de sortir de la maison, le fait d’être une fille est la cause principale qui m’empêche de créer des souvenirs avec mes amies dehors.",
   "translation": "When it comes to leaving the house, being a girl is the main reason I’m stopped from making memories with my friends outside."
  },
  {
   "theme": "Household & domestic roles",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "During Ramadan I always do the dishes, and whenever I ask my mom to tell my brother to do them instead, she keeps telling me to leave him alone."
  },
  {
   "theme": "Household & domestic roles",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "My mom would make me make my brother breakfast — and I’m younger than him. I was told I should cook and clean, that she was just ‘training me for my future husband’."
  },
  {
   "theme": "Sibling & family rules",
   "lang": "English",
   "who": "Female, 18–20",
   "text": "My brother has completely different rules and much more leeway, despite being younger than me."
  },
  {
   "theme": "Sibling & family rules",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "My mom and my grandma always buy a lot of things for my brother, but I rarely get anything."
  },
  {
   "theme": "Career & marriage expectations",
   "lang": "English",
   "who": "Female, 18–20",
   "text": "I can’t pursue my studies abroad because I’m a girl and I’m expected to take care of my family."
  },
  {
   "theme": "Career & marriage expectations",
   "lang": "English",
   "who": "Female, 14–17",
   "text": "I was told my athletic dreams aren’t as valuable because of the so-called ‘duties’ people expect from women. My goals are just as important."
  },
  {
   "theme": "Career & marriage expectations",
   "lang": "English",
   "who": "Male, 14–17",
   "text": "My parents told me I must have a well-paid job even if I don’t like it, because I’m a man and I have to provide for my future family."
  },
  {
   "theme": "Sibling & family rules",
   "lang": "Arabic",
   "who": "Female, 14–17",
   "text": "شعرتُ بأنني عوملتُ بشكل مختلف بسبب جنسي عندما تمّ التقليل من دوري في عملٍ جماعي، رغم امتلاكي الكفاءة نفسها.",
   "translation": "I felt treated differently because of my gender when my role in a group project was downplayed, even though I had the same competence as everyone else."
  }
 ],
 "bodyVoices": [
  {
   "lang": "English",
   "who": "Female, 14–17",
   "text": "I have always been judged for being too tall, and it impacted my self-esteem a lot."
  },
  {
   "lang": "English",
   "who": "Male, 14–17",
   "text": "People used to mock me for my skinny body. It was painful, so months later I started going to the gym."
  },
  {
   "lang": "English",
   "who": "Female, 14–17",
   "text": "I’ve been called fat many times, and I actually developed disordered eating over time."
  },
  {
   "lang": "French",
   "who": "Male, 18–20",
   "text": "Une partie de mon corps est assez développée pour un homme, donc je ne peux pas mettre les vêtements que je veux.",
   "translation": "One part of my body is quite developed for a man, so I can’t wear the clothes I want."
  }
 ],
 "themes": [
  {
   "name": "School & classroom",
   "count": 18
  },
  {
   "name": "Sibling & family rules",
   "count": 18
  },
  {
   "name": "Mobility & going out",
   "count": 13
  },
  {
   "name": "Sports & PE",
   "count": 10
  },
  {
   "name": "Career & marriage",
   "count": 8
  },
  {
   "name": "Household & domestic",
   "count": 8
  }
 ]
};
